---
# Copyright © 2020-2022 Matt Robinson
#
# SPDX-License-Identifier: MIT

name: Build
on:
  push:
    branches-ignore:
      - dependabot/**
      - update-version
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7a-linux-androideabi
          - aarch64-linux-android
          - i686-linux-android
          - x86_64-linux-android
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build script
        run: |
          ndk="$($ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
                 --list_installed | sed -E 's/( +[|] +)/|/g;s/ +$//' | \
                 grep '^  ndk' | cut -d '|' -f 4 | sort | head -n1)"
          ANDROID_NDK_HOME="$ANDROID_HOME/$ndk" ./build
        env:
          TARGET: ${{ matrix.target }}

      - name: Collect binaries and build info
        run: |
          mkdir output
          cp dropbear/dropbearmulti output

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: output

      - name: Upload build info as artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildinfo
          path: buildinfo
